# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rspec-rails-matchers}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Cyril David"]
  s.date = %q{2010-03-04}
  s.description = %q{Helps you write rspec with rails for fun}
  s.email = %q{cyx@sinefunc.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/rspec-rails-matchers.rb",
     "lib/rspec_rails_matchers/associations.rb",
     "lib/rspec_rails_matchers/associations/belong_to.rb",
     "lib/rspec_rails_matchers/associations/have_and_belong_to_many.rb",
     "lib/rspec_rails_matchers/associations/have_many.rb",
     "lib/rspec_rails_matchers/associations/have_one.rb",
     "lib/rspec_rails_matchers/associations/helpers.rb",
     "lib/rspec_rails_matchers/behavior.rb",
     "lib/rspec_rails_matchers/behavior/lint.rb",
     "lib/rspec_rails_matchers/message.rb",
     "lib/rspec_rails_matchers/validations.rb",
     "lib/rspec_rails_matchers/validations/confirmation_of.rb",
     "lib/rspec_rails_matchers/validations/length_of.rb",
     "lib/rspec_rails_matchers/validations/numericality_of.rb",
     "lib/rspec_rails_matchers/validations/presence_of.rb",
     "lib/rspec_rails_matchers/validations/uniqueness_of.rb",
     "rspec-rails-matchers.gemspec"
  ]
  s.homepage = %q{http://github.com/sinefunc/rspec-rails-matchers}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Rspec 2.0 only rails matchers}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

